---
- name: Enable iTerm2 automatic updates.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: SUEnableAutomaticChecks
    type: bool
    value: true
  tags: ['iterm2']

- name: Ensure iTerm directories are initialized if they are not already.
  ansible.builtin.file:
    path: "~/Library/Application Support/iTerm2/DynamicProfiles/"
    state: directory
    mode: "0755"
  tags: ["iterm2"]

- name: Ensure local DynamicProfiles are copied to iTerm2 directory.
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/Library/Application Support/iTerm2/DynamicProfiles/{{ item }}"
  loop:
    - "iterm2.json"
    - "iterm2_tmux.json"
  become: false
  tags: ["iterm2"]
