- name: Creates rectangle config directory.
  file:
    path: "~/Library/Application Support/Rectangle/"
    state: directory
- name: Copy rectangle config file.
  ansible.builtin.copy:
    src: "RectangleConfig.json"
    dest: "~/Library/Application Support/Rectangle/RectangleConfig-Ansible.json"
  become: false
  register: rectanglecopy
  tags: ["rectangle"]

- name: Copy rectangle config if changed
  ansible.builtin.copy:
    src: "~/Library/Application Support/Rectangle/RectangleConfig-Ansible.json"
    dest: "~/Library/Application Support/Rectangle/RectangleConfig.json"
  when: rectanglecopy.changed
  tags: ["rectangle"]