# Do sudo using Touch ID
- name: Set sudo via Touch ID
  become: true
  ansible.builtin.copy:
      dest: "/etc/pam.d/sudo_local"
      content: |
        # sudo_local: local config file which survives system update and is included for sudo
        # uncomment following line to enable Touch ID for sudo
        auth       sufficient     pam_tid.so
  tags:
    - touchid